apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: cloudops-pvc
  namespace: production-platform

spec:
  storageClassName: ""
  volumeName: cloudops-pv

  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi