apiVersion: v1
kind: ResourceQuota

metadata:
  name: production-quota
  namespace: production-platform

spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "20"
    persistentvolumeclaims: "5"